In [49]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

In [2]:
df = pd.read_csv('report.csv')
df

MIP      STDIP      EKIP       SIP         MC       STDC  \
0      137.218750  45.390655  0.034985  0.134409   3.204013  17.177857   
1       93.773438  41.883062  0.371402  1.291232   1.482441  12.959050   
2       73.632812  35.461218  1.153607  4.161082   2.099498  13.057474   
3       93.429688  39.883166  0.602060  1.518548   2.475753  14.146578   
4      131.625000  44.111896  0.108905  0.239879  33.888796  70.398342   
...           ...        ...       ...       ...        ...        ...   
17893  121.117188  50.127279 -0.017936 -0.193900   1.566890  10.804730   
17894  120.679688  40.918542  0.291465  0.627087   1.473244  13.912476   
17895  138.101562  47.935314 -0.181827 -0.283746   3.270903  16.963817   
17896  119.523438  44.198410  0.026662  0.352641   1.828595  12.674068   
17897  154.875000  48.590766 -0.285643  0.129281   4.153010  21.971915   

             EKC          SC  TARGET  
0       7.494588   74.003104       0  
1      12.242911  180.158844       0  
2      10.013591  140.894151       0  
3       8.770640  107.970173       0  
4       1.689460    1.031847       0  
...          ...         ...     ...  
17893  13.737064  269.096109       0  
17894  13.144044  203.416941       0  
17895   6.988850   63.043499       0  
17896  11.153939  166.582439       0  
17897   6.746838   52.230021       0  

[17898 rows x 9 columns]

In [6]:
df[((df['MIP'] >= 102.234375) & (df['MIP'] <= 102.6015625) & (df['TARGET'] == 0)) | ((df['MIP'] >= 77.4921875) & (df['MIP'] <= 83.7734375) & (df['TARGET'] == 1))]

MIP      STDIP      EKIP       SIP          MC       STDC  \
97     102.320312  45.574104  0.321909  0.379148    4.402174  22.540145   
155     80.640625  56.308821  1.481006  1.952136   27.807692  63.855448   
221    102.507812  58.882430  0.465318 -0.515088    1.677258  14.860146   
255    102.328125  48.980403  0.315729 -0.202183    1.898829  13.839040   
564    102.351562  35.394339  0.409204  1.810187    6.056020  30.250449   
...           ...        ...       ...       ...         ...        ...   
17467   83.773438  52.279031  1.206698  1.630834   97.373746  90.905524   
17486   81.718750  52.875286  1.482041  1.538289  170.656354  80.765608   
17585  102.359375  43.823106  0.242901  0.102978    3.076087  21.222584   
17690  102.546875  45.627031  0.445201  0.487925    2.580268  19.197210   
17783  102.570312  49.873227  0.451559  0.261429    2.708194  19.834288   

             EKC          SC  TARGET  
97      6.377098   47.256396       0  
155     2.179750    3.354892       1  
221    10.576487  127.393580       0  
255    11.619939  172.130373       0  
564     5.505104   31.174180       0  
...          ...         ...     ...  
17467   0.132639   -1.683188       1  
17486  -1.002570   -0.280001       1  
17585   7.502146   59.399329       0  
17690   8.953785   88.399977       0  
17783   8.078449   69.089674       0  

[204 rows x 9 columns]

In [62]:
df[((df['MIP'] >= 102.234375) & (df['MIP'] <= 102.6015625) & (df['TARGET'] == 0)) | ((df['MIP'] >= 77.4921875) & (df['MIP'] <= 83.7734375) & (df['TARGET'] == 1))].mean()

MIP       91.632123
STDIP     44.293987
EKIP       0.940249
SIP        2.274948
MC        22.377066
STDC      37.371435
EKC        6.330461
SC        69.007633
TARGET     0.495098
dtype: float64

In [63]:
new = df[((df['MIP'] >= 102.234375) & (df['MIP'] <= 102.6015625) & (df['TARGET'] == 0)) | ((df['MIP'] >= 77.4921875) & (df['MIP'] <= 83.7734375) & (df['TARGET'] == 1))]

In [64]:
predcors = new.drop('TARGET', axis=1)
predcors

MIP      STDIP      EKIP       SIP          MC       STDC  \
97     102.320312  45.574104  0.321909  0.379148    4.402174  22.540145   
155     80.640625  56.308821  1.481006  1.952136   27.807692  63.855448   
221    102.507812  58.882430  0.465318 -0.515088    1.677258  14.860146   
255    102.328125  48.980403  0.315729 -0.202183    1.898829  13.839040   
564    102.351562  35.394339  0.409204  1.810187    6.056020  30.250449   
...           ...        ...       ...       ...         ...        ...   
17467   83.773438  52.279031  1.206698  1.630834   97.373746  90.905524   
17486   81.718750  52.875286  1.482041  1.538289  170.656354  80.765608   
17585  102.359375  43.823106  0.242901  0.102978    3.076087  21.222584   
17690  102.546875  45.627031  0.445201  0.487925    2.580268  19.197210   
17783  102.570312  49.873227  0.451559  0.261429    2.708194  19.834288   

             EKC          SC  
97      6.377098   47.256396  
155     2.179750    3.354892  
221    10.576487  127.393580  
255    11.619939  172.130373  
564     5.505104   31.174180  
...          ...         ...  
17467   0.132639   -1.683188  
17486  -1.002570   -0.280001  
17585   7.502146   59.399329  
17690   8.953785   88.399977  
17783   8.078449   69.089674  

[204 rows x 8 columns]

In [65]:
target = new['TARGET']
target

97       0
155      1
221      0
255      0
564      0
        ..
17467    1
17486    1
17585    0
17690    0
17783    0
Name: TARGET, Length: 204, dtype: int64

In [66]:
scaler = MinMaxScaler()
norm = scaler.fit_transform(predcors)

In [67]:
np.mean(norm[:, 0])

0.5631337164610708

In [68]:
reg = LogisticRegression(random_state=2019, solver='lbfgs').fit(norm, target.values.ravel())

In [69]:
reg.predict(np.array([[0.237, 0.293, 0.897, 0.0, 0.841, 0.969, 0.138, 0.083]]))

array([1], dtype=int64)

In [70]:
reg.predict_proba(np.array([[0.237, 0.293, 0.897, 0.0, 0.841, 0.969, 0.138, 0.083]]))

array([[0.03591177, 0.96408823]])

In [44]:
kmeans = KMeans(n_clusters=2, max_iter=100, n_init=1)
model = kmeans.fit(norm)

In [42]:
alldistances = kmeans.fit_transform(np.array([[0.237, 0.293, 0.897, 0.0, 0.841, 0.969, 0.138, 0.083]]).reshape(-1,1))

In [43]:
alldistances

array([[0.0868    , 0.66533333],
       [0.1428    , 0.60933333],
       [0.7468    , 0.00533333],
       [0.1502    , 0.90233333],
       [0.6908    , 0.06133333],
       [0.8188    , 0.06666667],
       [0.0122    , 0.76433333],
       [0.0672    , 0.81933333]])

In [48]:
np.min(alldistances, axis=0)

array([0.0122    , 0.00533333])

In [71]:
neigh = KNeighborsClassifier(n_neighbors=5)
neigh.fit(norm, target)

KNeighborsClassifier()

In [72]:
neigh.predict(np.array([[0.237, 0.293, 0.897, 0.0, 0.841, 0.969, 0.138, 0.083]]))

array([1], dtype=int64)

In [73]:
neigh.kneighbors(np.array([[0.237, 0.293, 0.897, 0.0, 0.841, 0.969, 0.138, 0.083]]))

(array([[0.41551854, 0.4185572 , 0.44611942, 0.44723977, 0.45111229]]),
 array([[164, 187, 169, 136, 102]], dtype=int64))