In [23]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

In [2]:
df = pd.read_csv('pulsar_stars_new.csv')
df

MIP      STDIP      EKIP       SIP          MC       STDC  \
0      140.562500  55.683782 -0.234571 -0.699648    3.199833  19.110426   
1      102.507812  58.882430  0.465318 -0.515088    1.677258  14.860146   
2      103.015625  39.341649  0.323328  1.051164    3.121237  21.744669   
3      136.750000  57.178449 -0.068415 -0.636238    3.642977  20.959280   
4       88.726562  40.672225  0.600866  1.123492    1.178930  11.468720   
...           ...        ...       ...       ...         ...        ...   
17893  136.429688  59.847421 -0.187846 -0.738123    1.296823  12.166062   
17894  122.554688  49.485605  0.127978  0.323061   16.409699  44.626893   
17895  119.335938  59.935939  0.159363 -0.743025   21.430602  58.872000   
17896  114.507812  53.902400  0.201161 -0.024789    1.946488  13.381731   
17897   57.062500  85.797340  1.406391  0.089520  188.306020  64.712562   

             EKC          SC  TG  
0       7.975532   74.242225   0  
1      10.576487  127.393580   0  
2       7.735822   63.171909   0  
3       6.896499   53.593661   0  
4      14.269573  252.567306   0  
...          ...         ...  ..  
17893  15.450260  285.931022   0  
17894   2.945244    8.297092   0  
17895   2.499517    4.595173   0  
17896  10.007967  134.238910   0  
17897  -1.597527    1.429475   0  

[17898 rows x 9 columns]

In [38]:
data = df[( (df['MIP'] >= 87.5859375) & (df['MIP'] <= 88.484375) & (df['TG'] == 0) ) | ( (df['MIP'] >= 52.9296875) & (df['MIP'] <= 58.7890625) & (df['TG'] == 1) )]
data

MIP      STDIP      EKIP        SIP         MC       STDC  \
245    88.250000  39.046047  0.571522   1.470493   4.650502  25.669724   
508    53.789062  30.062085  3.231805  18.011655  30.670569  67.752058   
603    55.187500  35.726773  2.206251   8.562220  32.508361  59.498159   
628    87.750000  38.204630  0.851328   2.376166   2.226589  15.082094   
648    58.437500  47.269631  2.148539   4.683292  55.520067  74.838212   
...          ...        ...       ...        ...        ...        ...   
17460  88.367188  46.742625  0.729737   1.108588   3.726589  21.637049   
17628  87.984375  39.870099  0.620862   1.687396   1.372910  10.938322   
17670  87.742188  47.313325  0.369248   0.350295   3.006689  21.972732   
17681  87.906250  39.194116  0.806024   2.050931   2.346154  15.186816   
17830  87.625000  34.773149  0.712327   3.026128   2.178930  17.157048   

             EKC          SC  TG  
245     6.217865   40.987388   0  
508     1.972958    2.336556   1  
603     1.812744    2.443437   1  
628     9.076639  102.732359   0  
648     1.138116   -0.027806   1  
...          ...         ...  ..  
17460   6.614157   47.496511   0  
17628  14.907060  289.407265   0  
17670   7.793131   63.340975   0  
17681   8.811533   97.265489   0  
17830   9.315048   96.368709   0  

[202 rows x 9 columns]

In [39]:
predictors = data.drop('TG', axis = 1)
predictors

MIP      STDIP      EKIP        SIP         MC       STDC  \
245    88.250000  39.046047  0.571522   1.470493   4.650502  25.669724   
508    53.789062  30.062085  3.231805  18.011655  30.670569  67.752058   
603    55.187500  35.726773  2.206251   8.562220  32.508361  59.498159   
628    87.750000  38.204630  0.851328   2.376166   2.226589  15.082094   
648    58.437500  47.269631  2.148539   4.683292  55.520067  74.838212   
...          ...        ...       ...        ...        ...        ...   
17460  88.367188  46.742625  0.729737   1.108588   3.726589  21.637049   
17628  87.984375  39.870099  0.620862   1.687396   1.372910  10.938322   
17670  87.742188  47.313325  0.369248   0.350295   3.006689  21.972732   
17681  87.906250  39.194116  0.806024   2.050931   2.346154  15.186816   
17830  87.625000  34.773149  0.712327   3.026128   2.178930  17.157048   

             EKC          SC  
245     6.217865   40.987388  
508     1.972958    2.336556  
603     1.812744    2.443437  
628     9.076639  102.732359  
648     1.138116   -0.027806  
...          ...         ...  
17460   6.614157   47.496511  
17628  14.907060  289.407265  
17670   7.793131   63.340975  
17681   8.811533   97.265489  
17830   9.315048   96.368709  

[202 rows x 8 columns]

In [40]:
target = data['TG']
target

245      0
508      1
603      1
628      0
648      1
        ..
17460    0
17628    0
17670    0
17681    0
17830    0
Name: TG, Length: 202, dtype: int64

In [41]:
predictors_norm = MinMaxScaler().fit_transform(predictors)
predictors_norm

array([[0.99340804, 0.41988614, 0.05968589, ..., 0.19341118, 0.28232554,
        0.06102972],
       [0.02417051, 0.12089872, 0.82092666, ..., 0.6688676 , 0.12278051,
        0.00580772],
       [0.06350253, 0.3094203 , 0.52746404, ..., 0.57561305, 0.11675887,
        0.00596042],
       ...,
       [0.97912547, 0.69502225, 0.00180502, ..., 0.15164168, 0.34153199,
        0.09296719],
       [0.98373984, 0.42481391, 0.12678851, ..., 0.07497275, 0.37980868,
        0.14143652],
       [0.97582949, 0.27768355, 0.09997727, ..., 0.09723291, 0.3987333 ,
        0.14015525]])

In [42]:
np.mean(predictors_norm[:, 0])

0.5367376553080491

In [19]:
reg = LogisticRegression(random_state=10, solver='lbfgs')
reg.fit(predictors_norm, target)

LogisticRegression(random_state=10)

In [20]:
new_data = np.array([0.762, 0.309, 0.13, 0.91, 0.282, 0.396, 0.07, 0.016])
new_data

array([0.762, 0.309, 0.13 , 0.91 , 0.282, 0.396, 0.07 , 0.016])

In [22]:
reg.predict_proba([new_data])

array([[0.56074288, 0.43925712]])

In [33]:
neigh = KNeighborsClassifier(n_neighbors=5)
neigh.fit(predictors_norm, target)

KNeighborsClassifier()

In [34]:
neigh.kneighbors_graph([new_data])


<1x201 sparse matrix of type '<class 'numpy.float64'>'
	with 5 stored elements in Compressed Sparse Row format>

In [35]:
neigh.predict_proba([new_data])

array([[0.6, 0.4]])

In [36]:
neigh.predict([new_data])

array([0], dtype=int64)

In [81]:
sum = 0
for kek in (neigh.kneighbors([new_data], 20)[1]).reshape(-1, 1):
    if target.iloc[kek].values == 1:
        sum += 1

In [82]:
sum

10

In [70]:
sum

0

In [54]:
neighbours

[]