In [6]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
import numpy as np

In [3]:
data = pd.read_csv('data.csv')
data

id   X   Y  Class
0   1  96  11      1
1   2  76  24      1
2   3  98  11      0
3   4  89  71      0
4   5  87  99      0
5   6  31  40      0
6   7  73  35      1
7   8  33  30      0
8   9  87  88      1
9  10  81  30      1

In [31]:
distance = {}
new_obj = [68, 46]
for index, point in data.iterrows():
    X = point["X"]
    Y = point["Y"]
    euclidean = np.sqrt( (new_obj[0] - X)**2 +
                         (new_obj[1] - Y)**2)
    distance[f'{index}'] = euclidean
aa = sorted(distance.items(), key=lambda item: item[1])
dict(aa)

{'6': 12.083045973594572,
 '9': 20.615528128088304,
 '1': 23.40939982143925,
 '3': 32.64965543462902,
 '5': 37.48332962798263,
 '7': 38.48376280978771,
 '0': 44.82186966202994,
 '2': 46.09772228646444,
 '8': 46.09772228646444,
 '4': 56.302753041036986}

In [37]:
neighbour = KNeighborsClassifier(n_neighbors=3, p=2)
neighbour.fit(data[['X', 'Y']], data['Class'])

KNeighborsClassifier(n_neighbors=3)

In [44]:
neighbour.predict(np.array(new_obj).reshape(1, 2))

C:\Users\gto_n\anaconda3\envs\TrainingPrograms\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [46]:
neighbour_manhattan = KNeighborsClassifier(n_neighbors=3, p=1)
neighbour_manhattan.fit(data[['X', 'Y']], data['Class'])
neighbour_manhattan.predict(np.array(new_obj).reshape(1, 2))

C:\Users\gto_n\anaconda3\envs\TrainingPrograms\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [48]:
neighbour_manhattan.kneighbors(np.array(new_obj).reshape(1, 2))[0]

C:\Users\gto_n\anaconda3\envs\TrainingPrograms\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([[16., 29., 30.]])

In [49]:
neighbour_manhattan.kneighbors(np.array(new_obj).reshape(1, 2))[1]

C:\Users\gto_n\anaconda3\envs\TrainingPrograms\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([[6, 9, 1]], dtype=int64)