In [2]:
import pandas as pd
import sklearn
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [10]:
x = np.array([22, 19, 11, 7, 13, 20, 8, 12, 15, 23])
y = [45, 42, 23, 23, 23, 39, 19, 21, 28, 65]

In [12]:
reg = LinearRegression().fit(x.reshape(-1, 1), y)

In [22]:

r2_score(y, reg.predict(x.reshape(-1, 1)))

0.8012731648349211

In [16]:
x.mean()

15.0

In [18]:
np.array(y).mean()

32.8

In [14]:
reg.intercept_

-1.6594594594594625

In [15]:
reg.coef_

array([2.2972973])

In [3]:
candy = pd.read_csv('candy-data.csv')
candy

competitorname  chocolate  fruity  caramel  peanutyalmondy  nougat  \
0               100 Grand          1       0        1               0       0   
1            3 Musketeers          1       0        0               0       1   
2                One dime          0       0        0               0       0   
3             One quarter          0       0        0               0       0   
4               Air Heads          0       1        0               0       0   
..                    ...        ...     ...      ...             ...     ...   
65       Snickers Crisper          1       0        1               1       0   
66        Sour Patch Kids          0       1        0               0       0   
67  Sour Patch Tricksters          0       1        0               0       0   
68              Starburst          0       1        0               0       0   
69    Strawberry bon bons          0       1        0               0       0   

    crispedricewafer  hard  bar  pluribus  sugarpercent  pricepercent  \
0                  1     0    1         0         0.732         0.860   
1                  0     0    1         0         0.604         0.511   
2                  0     0    0         0         0.011         0.116   
3                  0     0    0         0         0.011         0.511   
4                  0     0    0         0         0.906         0.511   
..               ...   ...  ...       ...           ...           ...   
65                 1     0    1         0         0.604         0.651   
66                 0     0    0         1         0.069         0.116   
67                 0     0    0         1         0.069         0.116   
68                 0     0    0         1         0.151         0.220   
69                 0     1    0         1         0.569         0.058   

    winpercent  Y  
0    66.971725  1  
1    67.602936  1  
2    32.261086  0  
3    46.116505  0  
4    52.341465  1  
..         ... ..  
65   59.529251  1  
66   59.863998  1  
67   52.825947  1  
68   67.037628  1  
69   34.578991  0  

[70 rows x 14 columns]

In [28]:
# candy_predictors_train = candy[['chocolate', 'fruity', 'caramel', 'peanutyalmondy', 'nougat', 'crispedricewafer', 'hard', 'bar', 'pluribus', 'sugarpercent', 'pricepercent'] & candy['competitorname'] != 'Caramel Apple Pops']
candy_train = candy[(candy['competitorname'] != 'Caramel Apple Pops')
& (candy['competitorname'] != 'Hersheys Kisses')]
candy_test1 = candy[(candy['competitorname'] == 'Caramel Apple Pops')]
candy_test2 = candy[(candy['competitorname'] == 'Hersheys Kisses')]
# candy_response_train = candy['winpercent']

In [17]:
candy_train

competitorname  chocolate  fruity  caramel  peanutyalmondy  nougat  \
0               100 Grand          1       0        1               0       0   
1            3 Musketeers          1       0        0               0       1   
2                One dime          0       0        0               0       0   
3             One quarter          0       0        0               0       0   
4               Air Heads          0       1        0               0       0   
..                    ...        ...     ...      ...             ...     ...   
65       Snickers Crisper          1       0        1               1       0   
66        Sour Patch Kids          0       1        0               0       0   
67  Sour Patch Tricksters          0       1        0               0       0   
68              Starburst          0       1        0               0       0   
69    Strawberry bon bons          0       1        0               0       0   

    crispedricewafer  hard  bar  pluribus  sugarpercent  pricepercent  \
0                  1     0    1         0         0.732         0.860   
1                  0     0    1         0         0.604         0.511   
2                  0     0    0         0         0.011         0.116   
3                  0     0    0         0         0.011         0.511   
4                  0     0    0         0         0.906         0.511   
..               ...   ...  ...       ...           ...           ...   
65                 1     0    1         0         0.604         0.651   
66                 0     0    0         1         0.069         0.116   
67                 0     0    0         1         0.069         0.116   
68                 0     0    0         1         0.151         0.220   
69                 0     1    0         1         0.569         0.058   

    winpercent  Y  
0    66.971725  1  
1    67.602936  1  
2    32.261086  0  
3    46.116505  0  
4    52.341465  1  
..         ... ..  
65   59.529251  1  
66   59.863998  1  
67   52.825947  1  
68   67.037628  1  
69   34.578991  0  

[68 rows x 14 columns]

In [26]:
candy_test1

competitorname  chocolate  fruity  caramel  peanutyalmondy  nougat  \
9  Caramel Apple Pops          0       1        1               0       0   

   crispedricewafer  hard  bar  pluribus  sugarpercent  pricepercent  \
9                 0     0    0         0         0.604         0.325   

   winpercent  Y  
9   34.517681  0

In [18]:
reg = LinearRegression().fit(
    candy_train[['chocolate', 'fruity', 'caramel', 'peanutyalmondy', 'nougat', 'crispedricewafer', 'hard', 'bar', 'pluribus', 'sugarpercent', 'pricepercent']],
    candy_train['winpercent'])

In [27]:
reg.predict(candy_test1[['chocolate', 'fruity', 'caramel', 'peanutyalmondy', 'nougat', 'crispedricewafer', 'hard', 'bar', 'pluribus', 'sugarpercent', 'pricepercent']])

array([53.68280247])

In [29]:
reg.predict(candy_test2[['chocolate', 'fruity', 'caramel', 'peanutyalmondy', 'nougat', 'crispedricewafer', 'hard', 'bar', 'pluribus', 'sugarpercent', 'pricepercent']])

array([58.8607841])

In [34]:
reg.predict(np.array([1, 0, 0, 1, 1, 0, 0, 1, 1, 0.624, 0.438]).reshape(1, -1))

C:\Users\gto_n\anaconda3\envs\TrainingPrograms\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([64.69721336])